global:
  scrape_interval: 5s      # Ideal para monitorar HFT sem derrubar a CPU
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'quantum_trader'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000'] # Aponta para o servidor de métricas interno do seu bot

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']